### ISSUE TITLE
New command to generate AND show the APP_KEY

### ISSUE THREAD

**Issue by dataCore** [comoser/snipe-it-docker-compose#1]
I just had to google how to generate AND show the generated APP_KEY. On the current version (v5.1.7) of SnipeIT, just generating the key won't show you the key to put it into the .env file. I had to add _--show_ to the command:
`  php artisan key:generate --show`

**Comment by comoser** [comment]
oh I wasn't aware of this! Thanks @dataCore, I'll fix the docs right away
