### ISSUE TITLE
Not possible to make a zip backup

### ISSUE THREAD

**Issue by szopatrik** [comoser/snipe-it-docker-compose#3]
![port](https://user-images.githubusercontent.com/70323453/133056320-0acd7948-df74-41da-95c3-a71d89126a1a.png)

Hi there, i think you could add  "MYSQL_PORT_3306_TCP_PORT=3306" as a second line in your config file in README.md
Otherwise its not possible to make a backup using UI. >>> https://snipe-it.readme.io/docs/docker
This could help other not to debug it as i did :-) 
Thanks. Patrik

**Comment by comoser** [comment]
@szopatrik thank you for this feedback!
I was not aware of this. I have indeed added this to the `README.md` file 👍
